name : mathskit
description: MathsKit is a kit to do maths built in Flutter
environment:
  sdk: '^3.10.0'
dependencies:
  flutter:
    sdk : flutter
  quadratic_solve: ^1.0.0
flutter:
  uses-material-design: true


